{% set name = "molecule" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: baee178decff57fb4e2470af1aefc187d8f7a319696de033feb3614295bbfd3d

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - molecule = molecule.__main__:main

requirements:
  host:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*
    - pip
    - setuptools_scm >=1.15.0
    - setuptools_scm_git_archive >=1.0

  run:
    - python >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*

    - ansible >=2.8
    - backports.functools_lru_cache
    - cerberus >=1.3.1
    - click >=7.0
    - click-completion >=0.5.1
    - click-help-colors >=0.6
    - colorama >=0.3.9
    - cookiecutter >=1.6.0
    - python-gilt >=1.2.1,< 2
    - Jinja2 >=2.10.1
    - paramiko >=2.5.0,< 3
    - pathlib2 # [py<32]
    - pexpect >=4.6.0,< 5
    - pluggy >=0.7.1,< 1.0
    - pre-commit >=1.17.0,< 2
    - PyYAML >=5.1,< 6
    - sh >=1.12.14
    - six >=1.11.0
    - subprocess32 # [py<35]
    - tabulate >=0.8.4
    - tree-format >=0.1.2
    - yamllint >=1.15.0,< 2

test:
  imports:
    - molecule

about:
  home: https://github.com/ansible/molecule
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Molecule aids in the development and testing of Ansible roles'

  description: |
    Molecule is designed to aid in the development and testing
    of Ansible roles.
    Molecule provides support for testing with multiple instances,
    operating systems and distributions, virtualization providers,
    test frameworks and testing scenarios.
    Molecule encourages an approach that results in consistently
    developed roles that are well-written, easily
    understood and maintained.
  doc_url: https://molecule.readthedocs.io/
  dev_url: https://github.com/ansible/molecule

extra:
  recipe-maintainers:
    - knightdave
