{% set name = "molecule" %}
{% set version = "5.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6238023d90b5c3392714686849776f42a049d9f3e44075d36ead9f8ff88c260d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - molecule = molecule.__main__:main
  skip: true  # [py < 39 or win]

requirements:
  host:
    - python
    - pip >=19.3.1
    - setuptools >=42
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.1
    - wheel >=0.33.6
  run:
    # core dependencies
    - python
    - ansible-compat >=2.1.0
    - ansible-core
    - cerberus >=1.3.1,!=1.3.3,!=1.3.4
    - click >=8.0,<9
    - click-help-colors >=0.9
    - cookiecutter >=1.7.3
    - enrich  >=1.2.7
    - Jinja2 >=2.11.3
    - packaging
    - pluggy >=0.7.1,<2
    - PyYAML >=5.1
    - rich >=9.5.1

    # lint
    - flake8 >=3.8.4
    - pre-commit >=1.21.0
    - yamllint

test:
  imports:
    - molecule
  commands:
    - molecule --version

about:
  home: https://github.com/ansible/molecule
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Molecule aids in the development and testing of Ansible roles

  description: |
    Molecule is designed to aid in the development and testing
    of Ansible roles.
    Molecule provides support for testing with multiple instances,
    operating systems and distributions, virtualization providers,
    test frameworks and testing scenarios.
    Molecule encourages an approach that results in consistently
    developed roles that are well-written, easily
    understood and maintained.
  doc_url: https://molecule.readthedocs.io/
  dev_url: https://github.com/ansible/molecule

extra:
  recipe-maintainers:
    - knightdave
    - tschoonj
