{% set name = "molecule" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 31cbcdafb96a3e0df2a02ab49b4a4ce7d0c3129b34c351935612bf8097c999e2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  entry_points:
    - molecule = molecule.__main__:main
  skip: true  # [py < 37 or win]

requirements:
  host:
    - python
    - pip >=19.3.1
    - setuptools >=42
    - setuptools_scm >=3.5.0
    - setuptools_scm_git_archive >=1.1
    - wheel >=0.33.6
  run:
    # core dependencies
    - python
    - ansible-compat
    - ansible-lint >=5.0.10
    - cerberus >=1.3.1
    - click >=8.0,<9
    - click-help-colors >=0.9
    - cookiecutter >=1.7.3
    - dataclasses  # [py < 37]
    - enrich  >=1.2.5
    - Jinja2 >=2.10.1
    - packaging
    - paramiko >=2.5.0,<3
    - pluggy >=0.7.1,<1.0
    - PyYAML >=5.1,< 6
    - rich >=9.5.1
    - subprocess-tee >=0.2.0
    - setuptools >=42
    - yamllint >=1.15.0,< 2
    - python-selinux  # [linux]

    # ansible
    - ansible >=2.10

    # test
    - ansi2html >=1.6.0
    - pexpect >=4.8.0,<5
    - pytest-cov >=2.10.1
    - pytest-helpers-namespace >=2019.1.8
    - pytest-html >=3.0.0
    - pytest-mock >=3.3.1
    - pytest-plus >=0.2
    - pytest-testinfra >=6.1.0
    - pytest-verbose-parametrize >=1.7.0
    - pytest-xdist >=2.1.0
    - pytest >=6.1.2

    # lint
    - flake8 >=3.8.4
    - pre-commit >=1.21.0
    - yamllint

test:
  imports:
    - molecule
  commands:
    - molecule --version

about:
  home: https://github.com/ansible/molecule
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Molecule aids in the development and testing of Ansible roles

  description: |
    Molecule is designed to aid in the development and testing
    of Ansible roles.
    Molecule provides support for testing with multiple instances,
    operating systems and distributions, virtualization providers,
    test frameworks and testing scenarios.
    Molecule encourages an approach that results in consistently
    developed roles that are well-written, easily
    understood and maintained.
  doc_url: https://molecule.readthedocs.io/
  dev_url: https://github.com/ansible/molecule

extra:
  recipe-maintainers:
    - knightdave
    - tschoonj
